# This is a basic workflow to help you get started with Actions

name: CI-for-building-project-and-running-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
        # The checkout step downloads a copy of your repository on the runner.
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        # The setup-java step configures the Java 11 JDK by Adoptium.
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
      # The "Build with Maven" step runs the Maven package target
      # in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
        run: mvn --batch-mode --update-snapshots verify
        
