# This is a basic workflow to help you get started with Actions

name: CI-for-building-project-and-running-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@develop
    - name: Test
      uses: skx/github-action-tester@master
      with:
        script: .github/fast-tests.sh
